/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
//package com.gui;

//import com.controller.EditProjectInfoController;
//import com.gui.EditTaskInfoGUIJFRAME;
package ooadproject;
import java.awt.CardLayout;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JTable;
import javax.swing.table.TableColumn;

/**
 *
 * @author Coolth
 */
public class EditProjectInfoGUI extends javax.swing.JPanel {
    public static String passprojecId;
    private EditProjectInfoController editprojectInfoController;
    private TableColumn column = null;
    static EditTaskInfoGUIJFRAME editTaskInfoGuiframe;
    /**
     * Creates new form Edit
     */
    public EditProjectInfoGUI() {
        editprojectInfoController = new EditProjectInfoController(this);
        initComponents();
        addJTable();
    }
    public void addJTable() {
        projectInfoTable.getSelectionModel().addListSelectionListener(editprojectInfoController);  
        for ( int i = 0 ; i < 10; i ++){
            column = projectInfoTable.getColumnModel().getColumn(i);
            column.setPreferredWidth(10);
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     * @param value
     */
    @SuppressWarnings("unchecked")
    public void setProjectIdTextField(String value){
        projectIdTexefield.setText(value);
        passprojecId = projectIdTexefield.getText();
    }
    public void setEquipmentNameTextField(String value) {
	equipmentNameTextField.setText(value);
    }
    public void setEstimatedCostTextField(String value) {
	estimatedCostTextField.setText(value);
    }
    public void setProjectedCostTextField(String value) {
	projectedCostTextField.setText(value);
    }
    public void setProjectNameTextField(String value) {
	projectNameTextField.setText(value);
    }
    public void setProjectStartDateTextField(String value) {
	projectStartDateTextField.setText(value);
    }
    public void setProjectEndDateTextField(String value) {
	projectEndDateTextField.setText(value);
    }
    public void setProjectDescriptionTextArea1(String value) {
	projectDescriptionTextArea.setText(value);
    }
    public void setProjectOutcomeTextField(String value) {
        projectOutcomeTextField.setText(value);
    }
    public void setStatusTextField(String value) {
        statusTextField.setText(value);
    }
    public void setProjectCategoryTextField(String value) {
        projectCategoryTextField.setText(value);
    }
    public void setEquipmentLinkTextField(String value){
        equipmentLinkTextField.setText(value);
    }
//    public void updateTable() {
//	projectInfoTable.setModel(editprojectInfoController.getTableModel());
//    }             
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        emptyBorder1 = (javax.swing.border.EmptyBorder)javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1);
        buttonGroup1 = new javax.swing.ButtonGroup();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel14 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        projectNameTextField = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        projectStartDateTextField = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        projectEndDateTextField = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        projectDescriptionTextArea = new javax.swing.JTextArea();
        updateButton = new javax.swing.JButton();
        jLabel13 = new javax.swing.JLabel();
        projectOutcomeTextField = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        equipmentNameTextField = new javax.swing.JTextField();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        estimatedCostTextField = new javax.swing.JTextField();
        jLabel17 = new javax.swing.JLabel();
        projectedCostTextField = new javax.swing.JTextField();
        equipmentLinkTextField = new javax.swing.JTextField();
        projectCategoryTextField = new javax.swing.JTextField();
        statusTextField = new javax.swing.JTextField();
        jLabel20 = new javax.swing.JLabel();
        projectIdTexefield = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        projectInfoTable = new javax.swing.JTable();
        EditTask = new javax.swing.JButton();

        jLabel14.setText("Project Budget");

        setBackground(new java.awt.Color(255, 255, 255));
        setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Edit Project Info", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        jLabel4.setText("Project Name ");

        projectNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectNameTextFieldActionPerformed(evt);
            }
        });

        jLabel7.setText("Start Date");

        projectStartDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectStartDateTextFieldActionPerformed(evt);
            }
        });

        jLabel8.setText("End Date");

        projectEndDateTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectEndDateTextFieldActionPerformed(evt);
            }
        });

        jLabel11.setText("Project Status");

        jLabel12.setText("Project Description ");

        projectDescriptionTextArea.setColumns(20);
        projectDescriptionTextArea.setRows(5);
        jScrollPane1.setViewportView(projectDescriptionTextArea);

        updateButton.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        updateButton.setText("Update");
        updateButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                updateButtonActionPerformed(evt);
            }
        });

        jLabel13.setText("Project Outcome");

        projectOutcomeTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectOutcomeTextFieldActionPerformed(evt);
            }
        });

        jLabel5.setText("Project Category");

        jLabel9.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel9.setText("Timeline Details :");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel2.setText("Budget Details :");

        jLabel6.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        jLabel6.setText("Basic Details");

        jLabel10.setText("Equipment Name");

        equipmentNameTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentNameTextFieldActionPerformed(evt);
            }
        });

        jLabel15.setText("Equipment Link");

        jLabel16.setText("Estimated Cost");

        estimatedCostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                estimatedCostTextFieldActionPerformed(evt);
            }
        });

        jLabel17.setText("Projected Cost");

        projectedCostTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectedCostTextFieldActionPerformed(evt);
            }
        });

        equipmentLinkTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                equipmentLinkTextFieldActionPerformed(evt);
            }
        });

        projectCategoryTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectCategoryTextFieldActionPerformed(evt);
            }
        });

        jLabel20.setText("Project Id");

        projectIdTexefield.setEditable(false);
        projectIdTexefield.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                projectIdTexefieldActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel7)
                            .addComponent(jLabel5)
                            .addComponent(jLabel11)
                            .addComponent(jLabel13)
                            .addComponent(jLabel9)
                            .addComponent(jLabel6)
                            .addComponent(jLabel8)
                            .addComponent(jLabel20))
                        .addGap(48, 48, 48)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(projectNameTextField, javax.swing.GroupLayout.DEFAULT_SIZE, 123, Short.MAX_VALUE)
                            .addComponent(projectOutcomeTextField)
                            .addComponent(projectStartDateTextField)
                            .addComponent(projectEndDateTextField)
                            .addComponent(projectCategoryTextField)
                            .addComponent(statusTextField)
                            .addComponent(projectIdTexefield))
                        .addGap(117, 117, 117)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel12)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 299, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2)
                                    .addComponent(jLabel10)
                                    .addComponent(jLabel15, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(jLabel16, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 81, Short.MAX_VALUE)
                                        .addComponent(jLabel17, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(equipmentNameTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(estimatedCostTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(equipmentLinkTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(projectedCostTextField, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(349, 349, 349)
                        .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(16, 16, 16)
                .addComponent(jLabel6)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(10, 10, 10)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel20)
                            .addComponent(projectIdTexefield, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4)
                            .addComponent(projectNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 28, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel5)
                            .addComponent(projectCategoryTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(statusTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 27, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(projectOutcomeTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(28, 28, 28)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(projectStartDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(projectEndDateTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel8)
                            .addComponent(projectedCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(30, 30, 30))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel12)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel10)
                            .addComponent(equipmentNameTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel15)
                            .addComponent(estimatedCostTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel16)
                            .addComponent(equipmentLinkTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel17)
                        .addGap(38, 38, 38)))
                .addComponent(updateButton, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(141, 141, 141))
        );

        projectInfoTable.setModel(editprojectInfoController.getTableModel()
        );
        jScrollPane2.setViewportView(projectInfoTable);

        EditTask.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        EditTask.setText("EditProjectTask");
        EditTask.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EditTaskMouseClicked(evt);
            }
        });
        EditTask.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EditTaskActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 836, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(EditTask)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 467, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(EditTask, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 56, Short.MAX_VALUE)))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents
    
    private void projectNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectNameTextFieldActionPerformed

    private void projectStartDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectStartDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectStartDateTextFieldActionPerformed

    private void projectEndDateTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectEndDateTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectEndDateTextFieldActionPerformed

    private void updateButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_updateButtonActionPerformed
        // TODO add your handling code here:
        String[] array = new String[projectInfoTable.getColumnCount()+1];
                array[0] = projectIdTexefield.getText();
		array[1] = projectNameTextField.getText();
                array[2] = projectDescriptionTextArea.getText();
                array[3] = statusTextField.getText();
                array[4] = projectCategoryTextField.getText();
		array[5] = projectOutcomeTextField.getText();
		array[6] = projectStartDateTextField.getText();
                array[7] = projectEndDateTextField.getText();
                array[8] = equipmentNameTextField.getText();
                array[9] = estimatedCostTextField.getText();
                array[10] = projectedCostTextField.getText(); 
                array[11] = equipmentLinkTextField.getText();     
		int row = projectInfoTable.getSelectedRow();
		editprojectInfoController.updateRow(String.valueOf(row), array);
    }//GEN-LAST:event_updateButtonActionPerformed

    private void estimatedCostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_estimatedCostTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_estimatedCostTextFieldActionPerformed

    private void projectOutcomeTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectOutcomeTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectOutcomeTextFieldActionPerformed

    private void equipmentNameTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentNameTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentNameTextFieldActionPerformed

    private void projectedCostTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectedCostTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectedCostTextFieldActionPerformed

    private void equipmentLinkTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_equipmentLinkTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_equipmentLinkTextFieldActionPerformed

    private void projectCategoryTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectCategoryTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectCategoryTextFieldActionPerformed

    private void projectIdTexefieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_projectIdTexefieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_projectIdTexefieldActionPerformed

    private void EditTaskMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EditTaskMouseClicked

         editTaskInfoGuiframe= new EditTaskInfoGUIJFRAME();
        editTaskInfoGuiframe.setVisible(true);

    }//GEN-LAST:event_EditTaskMouseClicked

    private void EditTaskActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EditTaskActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_EditTaskActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton EditTask;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.border.EmptyBorder emptyBorder1;
    private javax.swing.JTextField equipmentLinkTextField;
    private javax.swing.JTextField equipmentNameTextField;
    private javax.swing.JTextField estimatedCostTextField;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField projectCategoryTextField;
    private javax.swing.JTextArea projectDescriptionTextArea;
    private javax.swing.JTextField projectEndDateTextField;
    private javax.swing.JTextField projectIdTexefield;
    private javax.swing.JTable projectInfoTable;
    private javax.swing.JTextField projectNameTextField;
    private javax.swing.JTextField projectOutcomeTextField;
    private javax.swing.JTextField projectStartDateTextField;
    private javax.swing.JTextField projectedCostTextField;
    private javax.swing.JTextField statusTextField;
    private javax.swing.JButton updateButton;
    // End of variables declaration//GEN-END:variables
}
