/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooadproject;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.GridBagLayout;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javafx.embed.swing.JFXPanel;
import javafx.scene.control.ScrollBar;
import javax.swing.ButtonGroup;
import javax.swing.ImageIcon;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JLabel;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import java.awt.Dimension;
import java.awt.Graphics;
import java.awt.Image;

/**
 *
 * @author Manish
 */
public class LaunchApplication extends javax.swing.JPanel {

    /**
     * Creates new form PanelAlignment
     */
    Login log;
    JMenuBar mbar;
    JMenu menu;
    JMenuItem item;
    static JFrame frame;
    JRadioButton jrb;
    JRadioButton jrb1;
    JScrollPane jp;
    JPanel PaneForRegisterLogin;
    JPanel RegisterPanel;
    JPanel cards;
    String register = "Register";
    String Login = "Login";
    String Search = "Search";
    JPanel SearchPanel;
    JPanel pane1;
    JLabel label;
    ScrollBar scrollbar;
    public LaunchApplication() {
        
    initComponents();
    
       
    }

    /*public void actionPerformed(ActionEvent e) {
        System.out.println("hi");
        
        LaunchApplication la=new LaunchApplication();
        Search se=new Search();
        SearchPanel=new JPanel(new GridBagLayout());
        SearchPanel.add(se);
        //createAndShowGUI();
      // cards=new JPanel(new CardLayout());
        //cards.add(SearchPanel,Search);
        LoginPanel.setVisible(false);
        log.jPanel2.setVisible(false);
        log.jPanel1.setVisible(false);
        log.setVisible(false);
       frame.remove(jPanel2);
       frame.add(SearchPanel);
       //cards.setVisible(true);
       // CardLayout cl = (CardLayout) (cards.getLayout());
       // cl.show(cards, Search);

    }*/

    public void addComponentToPane(Container pane) {

        /*RadioButtonForm rbf=new RadioButtonForm();
         //jrb=new JRadioButton(Login);
         //jrb1=new JRadioButton(register);
         mbar=new JMenuBar();
         menu=new JMenu("Options");
         item=new JMenuItem("open");
         item.add(jRadioButton1);
         item.add(jRadioButton2);
         menu.add(item);
         mbar.add(menu);
        
         jPanel3.setLayout(new CardLayout());
         jPanel3.add(new JPanel(),"empty panel");
         //jPanel3.add(new JPanel(),"empty panel");
         jPanel3.add(mbar,"open");
         // jPanel3.add(jrb1,register);
         CardLayout cd=(CardLayout)jPanel3.getLayout();
         cd.show(jPanel3, "open");*/
        //cd.show(jPanel3, register);
        RegisterPanel = new JPanel(new GridBagLayout());
        RegisterPanel.setName(register);
        
         log = new Login();
        RegisterPanel.add( log);
        JButton jb=new JButton();
        
        //Search search=new Search();
        //LoginPanel.add(log);
       
        
        //card panel is creating
        cards = new JPanel(new CardLayout());
        //adding both panel to cards
        cards.add(LoginPanel, Login);
        //cards.add(RegisterPanel, register);
        
        cards.setVisible(false);
        pane1=new JPanel(new BorderLayout());
        pane1.add(jPanel1, BorderLayout.PAGE_START);
        //pane.add(jPanel2,BorderLayout.CENTER);
        //pane1.add(jPanel3, BorderLayout.WEST);
        pane1.add(RegisterPanel,BorderLayout.CENTER);
        
         JScrollPane scrollPane = new JScrollPane(pane1);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setBounds(50, 30, 300, 500);
        pane.add(scrollPane);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooadproject/fil-3squares-02.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 120));
        jPanel2.setLayout(new java.awt.BorderLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoginPanel.setPreferredSize(new java.awt.Dimension(434, 102));
        LoginPanel.setLayout(new java.awt.GridBagLayout());
        jPanel2.add(LoginPanel, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
public static void createAndShowGUI() {
        //Create and set up the window.
        frame = new JFrame("Frugal Lab Application");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Create and set up the content pane.
        LaunchApplication demo = new LaunchApplication();
        demo.addComponentToPane(frame.getContentPane());

        //Display the window.
        frame.pack();
        frame.setSize(800, 600);
        frame.setVisible(true);

    }

    public static void main(String[] args) {
        /* Use an appropriate Look and Feel */
        try {
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        /* Turn off metal's use of bold fonts */
        UIManager.put("swing.boldMetal", Boolean.FALSE);

        //Schedule a job for the event dispatch thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }
}
