/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooadproject;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.GridBagLayout;
import javafx.embed.swing.JFXPanel;
import javax.swing.ButtonGroup;
import javax.swing.JFrame;
import javax.swing.JPanel;
import javax.swing.JRadioButton;
import javax.swing.JScrollPane;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;

/**
 *
 * @author Manish
 */
public class MasterPanelFOrProjectPage extends javax.swing.JPanel {

    /**
     * Creates new form PanelAlignment
     */
    JRadioButton jrb;
    JRadioButton jrb1;
    JScrollPane jp;
    JPanel PaneForRegisterLogin;
    JPanel RegisterPanel;
    JPanel cards;
     String register="Register";
     String Search="Search";
     JPanel pane1;
     static JFrame frame;
    public MasterPanelFOrProjectPage() {
        initComponents();
    }
    public void addComponentToPane(Container pane)
    {
       
       /*RadioButtonForm rbf=new RadioButtonForm();
        jrb=new JRadioButton(Login);
        jrb1=new JRadioButton(register);
         jPanel3.setLayout(new CardLayout());
         jPanel3.add(new JPanel(),"empty panel");
         //jPanel3.add(new JPanel(),"empty panel");
        jPanel3.add(rbf,Login);
       // jPanel3.add(jrb1,register);
        CardLayout cd=(CardLayout)jPanel3.getLayout();
        cd.show(jPanel3, Login);
        //cd.show(jPanel3, register);*/
        RegisterPanel=new JPanel(new GridBagLayout());
        RegisterPanel.setName(register);
       // Register reg=new Register();
        ActivityPage act=new ActivityPage();
        RegisterPanel.add(act);
       // Login log=new Login();
        SearchProject search=new SearchProject();
        LoginPanel.add(search);
        
       /* cards=new JPanel(new CardLayout());
       
        cards.add(LoginPanel,Search);
        cards.add(RegisterPanel,register);
         cards.setVisible(false);*/
         //JScrollPane scroll=new JScrollPane(cards);
       pane1=new JPanel(new BorderLayout());
        pane1.add(jPanel1, BorderLayout.PAGE_START);
        //pane.add(jPanel2,BorderLayout.CENTER);
        pane1.add(jPanel3, BorderLayout.WEST);
        pane1.add(LoginPanel,BorderLayout.CENTER);
        
         JScrollPane scrollPane = new JScrollPane(pane1);
        scrollPane.setHorizontalScrollBarPolicy(JScrollPane.HORIZONTAL_SCROLLBAR_ALWAYS);
        scrollPane.setVerticalScrollBarPolicy(JScrollPane.VERTICAL_SCROLLBAR_ALWAYS);
        scrollPane.setBounds(50, 30, 30, 50);
        pane.add(scrollPane);
    
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
                       
/*
    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        cards.setVisible(true);
         CardLayout cl = (CardLayout)(cards.getLayout());
        cl.show(cards, Search);
    }                                             

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        cards.setVisible(true);
         CardLayout cl = (CardLayout)(cards.getLayout());
        cl.show(cards, register);
    }                                             

*/
     @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        LoginPanel = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();

        setLayout(new java.awt.BorderLayout());

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooadproject/fil-3squares-02.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        add(jPanel1, java.awt.BorderLayout.CENTER);

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 51, 0), 5));
        jPanel2.setPreferredSize(new java.awt.Dimension(100, 120));
        jPanel2.setLayout(new java.awt.BorderLayout());

        LoginPanel.setBackground(new java.awt.Color(255, 255, 255));
        LoginPanel.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        LoginPanel.setPreferredSize(new java.awt.Dimension(434, 102));
        LoginPanel.setLayout(new java.awt.GridBagLayout());
        jPanel2.add(LoginPanel, java.awt.BorderLayout.CENTER);

        add(jPanel2, java.awt.BorderLayout.PAGE_START);

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0), 3));
        jPanel3.setPreferredSize(new java.awt.Dimension(175, 175));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1378, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 169, Short.MAX_VALUE)
        );

        add(jPanel3, java.awt.BorderLayout.PAGE_END);
    }// </editor-fold>                        

    // Variables declaration - do not modify                     
    private javax.swing.JPanel LoginPanel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    //private javax.swing.JRadioButton jRadioButton1;
    //private javax.swing.JRadioButton jRadioButton2;
    // End of variables declaration                   
public static void createAndShowGUI() {
        //Create and set up the window.
        frame = new JFrame("Frugal Lab Application");
       // frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
         
        //Create and set up the content pane.
        MasterPanelFOrProjectPage mpf = new MasterPanelFOrProjectPage();
        mpf.addComponentToPane(frame.getContentPane());
         
        //Display the window.
        frame.pack();
        frame.setSize(800, 600);
        frame.setVisible(true);
    }
     
    public static void main(String[] args) {
        /* Use an appropriate Look and Feel */
        try {
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        /* Turn off metal's use of bold fonts */
        UIManager.put("swing.boldMetal", Boolean.FALSE);
         
        //Schedule a job for the event dispatch thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }
}
