/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooadproject;

import java.text.SimpleDateFormat;
import java.util.ArrayList;
import javax.persistence.EntityManager;
import javax.swing.JComboBox;
import javax.swing.JTable;
import javax.swing.JTextField;
import java.util.List;
import java.util.Vector;
import javax.swing.JOptionPane;
import static ooadproject.CreateProject.pj1;
import ooadproject.EntityTables.Budget;
import ooadproject.EntityTables.Userroletask;
import ooadproject.EntityTables.Project;
import ooadproject.EntityTables.User;
import ooadproject.EntityTables.Task;
import ooadproject.EntityTables.Role;

/**
 *
 * @author komalshirore
 */
public class MemberPanel extends javax.swing.JPanel {

    UserJpaController u;

    TaskJpaController t;
    
    List<Project> projects;
    List<User> users;

    /**
     * Creates new form memberPanel
     */
    public MemberPanel() {
        initComponents();
        u = new UserJpaController(this);
        t = new TaskJpaController(this);
        users = u.getAllUsers();
        Vector userNames = new Vector<String>();
        for (User user : users) {
            userNames.add(user.getName());
        }
        userList.setListData(userNames);

        projects = u.getAllProjects();
        for (Project project : projects) {
            selectProject.addItem(project.getProjectName());
        }

    }

    public void setSelectProject(JComboBox selectProject) {
        this.selectProject = selectProject;
    }

    public void setMemberTaskField(JTextField memberTaskField) {
        this.memberTaskField = memberTaskField;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        memberInfoLabel = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        memberTask = new javax.swing.JLabel();
        memberTaskField = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        userList = new javax.swing.JList();
        cancel = new javax.swing.JButton();
        addMember = new javax.swing.JButton();
        selectProjectLabel = new javax.swing.JLabel();
        selectProject = new javax.swing.JComboBox();
        startDateLabel = new javax.swing.JLabel();
        endDateLabel = new javax.swing.JLabel();
        startDate = new com.toedter.calendar.JDateChooser();
        endDate = new com.toedter.calendar.JDateChooser();

        setBackground(new java.awt.Color(255, 255, 255));

        memberInfoLabel.setFont(new java.awt.Font("Lucida Grande", 1, 14)); // NOI18N
        memberInfoLabel.setText("Add Members to Project");

        jLabel1.setText("Select Team Member");

        memberTask.setText("Task Description");

        jScrollPane1.setViewportView(userList);

        cancel.setText("Cancel");

        addMember.setText("Add");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        selectProjectLabel.setText("Select Project");

        startDateLabel.setText("Start Date");

        endDateLabel.setText("End Date");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(memberInfoLabel)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(memberTask)
                            .addComponent(startDateLabel)
                            .addComponent(endDateLabel)
                            .addComponent(jLabel1)
                            .addComponent(selectProjectLabel))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(selectProject, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 185, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(cancel)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(addMember))
                                .addComponent(memberTaskField, javax.swing.GroupLayout.DEFAULT_SIZE, 185, Short.MAX_VALUE)
                                .addComponent(startDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(endDate, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addComponent(memberInfoLabel)
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(selectProjectLabel)
                                    .addComponent(selectProject, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(56, 56, 56)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel1)
                                        .addGap(58, 58, 58)))
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(memberTaskField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(memberTask))
                                .addGap(18, 18, 18)
                                .addComponent(startDateLabel))
                            .addComponent(startDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addComponent(endDateLabel))
                    .addComponent(endDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cancel)
                    .addComponent(addMember))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        // TODO add your handling code here:
        if(memberTaskField.getText().equals(""))
        {
            JOptionPane.showMessageDialog(this, "All fields are mandatory","Warning",JOptionPane.PLAIN_MESSAGE);
        }
        for (int index : userList.getSelectedIndices()) {
            User user = users.get(index);

            int selectedProjectIndex = selectProject.getSelectedIndex();
            if (projects.size() == 0) {
                throw new RuntimeException("No projects in the system");
            }

            Project project = projects.get(selectedProjectIndex);
            Task task = new Task();
            task.setUserId(new User(user.getUserId()));
            task.setProjectId(new Project(project.getProjectId()));
            task.setStartDate(startDate.getDate());
            task.setEndDate(endDate.getDate());
            task.setTaskDescr(memberTaskField.getText());
            t.createEntry(task);
              ProfilePage.frame.dispose();
         JOptionPane.showMessageDialog(this, "Member added successfully to the project!","Message",JOptionPane.PLAIN_MESSAGE);
         pj1=new ProfilePage();
      javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                pj1.createAndShowGUI();
            }
        });
        }

    }//GEN-LAST:event_addMemberActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton addMember;
    private javax.swing.JButton cancel;
    private com.toedter.calendar.JDateChooser endDate;
    private javax.swing.JLabel endDateLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel memberInfoLabel;
    private javax.swing.JLabel memberTask;
    private javax.swing.JTextField memberTaskField;
    private javax.swing.JComboBox selectProject;
    private javax.swing.JLabel selectProjectLabel;
    private com.toedter.calendar.JDateChooser startDate;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JList userList;
    // End of variables declaration//GEN-END:variables
}
