/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ooadproject;

import java.awt.BorderLayout;
import java.awt.CardLayout;
import java.awt.Container;
import java.awt.GridBagLayout;
import java.awt.event.MouseListener;
import javax.swing.JFrame;
import javax.swing.JMenu;
import javax.swing.JMenuBar;
import javax.swing.JMenuItem;
import javax.swing.JPanel;
import javax.swing.UIManager;
import javax.swing.UnsupportedLookAndFeelException;
import static ooadproject.EditProjectInfoGUI.editTaskInfoGuiframe;
import static ooadproject.Login.result;

/**
 *
 * @author KomalShirore
 */
public class ProfilePage extends javax.swing.JPanel {

    /**
     * Creates new form PanelAlignment
     */
    JMenuBar mbar;
    JMenu menu;
    JMenuItem item;
    static JFrame frame;
    ProjectModel projectModel;

    JPanel cards;
static AddUserInfoGUIJframe add;
    private String createProject = "CreateProject";
    JPanel CreateProjectPanel;

    private String personalInfoPage = "PersonalInfoPage";
    JPanel PersonalInfoPagePanel;

    private String memberPage = "MemberPage";
    JPanel MemberPanel;

    private String viewPage = "ViewPage";
    JPanel viewPanel;
    JPanel editProjectPanel;
    private String editProject="editProject";
    static MasterPanelFOrProjectPage ma;
    static CommunicationMain cm;

    public ProfilePage() {
        initComponents();
        if(!result[1].equals("admin"))
        {
            createProjectButton.setEnabled(false);
            editProjectButton.setEnabled(false);
            editInfoButton.setEnabled(false);
        }
        jLabel2.setText("Welcome, "+result[2]+"!");
    }

    public void addComponentToPane(Container pane) {

        //card panel is creating
        cards = new JPanel(new CardLayout());
        //adding both panel to cards

        viewPanel = new JPanel(new GridBagLayout());
        ViewPanel viewPage = new ViewPanel();
        viewPanel.setName(this.viewPage);
        viewPanel.add(viewPage);
        cards.add(viewPanel, this.viewPage);
        // Create Project
        CreateProjectPanel = new JPanel(new BorderLayout());
        CreateProject createproject = new CreateProject();
        CreateProjectPanel.setName(createProject);
        CreateProjectPanel.add(createproject,BorderLayout.PAGE_START);
        cards.add(CreateProjectPanel, createProject);
       EditProjectInfoGUI pr=new EditProjectInfoGUI();
       editProjectPanel=new JPanel(new BorderLayout());
       editProjectPanel.add(pr,BorderLayout.PAGE_START);
       cards.add(pr, editProject);
        cards.setVisible(false);

        PersonalInfoPagePanel = new JPanel(new GridBagLayout());
        EditUserInfoGUI userinfo=new EditUserInfoGUI();
        PersonalInfoPagePanel.setName(this.personalInfoPage);
        PersonalInfoPagePanel.add(userinfo);
        cards.add(PersonalInfoPagePanel, this.personalInfoPage);

        MemberPanel = new JPanel(new GridBagLayout());
        MemberPanel memberPage = new MemberPanel();
        MemberPanel.setName(this.memberPage);
        MemberPanel.add(memberPage);
        cards.add(MemberPanel, this.memberPage);

        cards.setVisible(true);

       // JPanel innerPanel = new JPanel(new BorderLayout());
        // innerPanel.add(jPanel3, BorderLayout.WEST);
        // innerPanel.add(jPanel2, BorderLayout.EAST);
        pane.add(jPanel1, BorderLayout.PAGE_START);
        pane.add(jPanel3, BorderLayout.WEST);
        pane.add(cards);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel5 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        searchButton = new javax.swing.JButton();
        createProjectButton = new javax.swing.JButton();
        editProjectButton = new javax.swing.JButton();
        editInfoButton = new javax.swing.JButton();
        addNewUserButton = new javax.swing.JButton();
        communicationButton = new javax.swing.JButton();
        lgButton = new javax.swing.JButton();
        addMember = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();

        jPanel1.setBackground(new java.awt.Color(204, 0, 0));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(51, 0, 51), 3));
        jPanel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPanel1.setPreferredSize(new java.awt.Dimension(50, 100));
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setBackground(new java.awt.Color(204, 0, 0));
        jLabel1.setFont(new java.awt.Font("Tahoma", 3, 24)); // NOI18N
        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/ooadproject/fil-3squares-02.jpg"))); // NOI18N
        jPanel1.add(jLabel1, new java.awt.GridBagConstraints());

        jPanel5.setBackground(new java.awt.Color(204, 0, 0));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jLabel2.setText("jLabel2");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap(45, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(41, 41, 41))
        );

        jPanel1.add(jPanel5, new java.awt.GridBagConstraints());

        jPanel4.setLayout(new java.awt.GridLayout(1, 0));

        jPanel3.setBackground(new java.awt.Color(204, 0, 0));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 0, 0), 3));
        jPanel3.setPreferredSize(new java.awt.Dimension(175, 175));

        searchButton.setText("Search Projects");
        searchButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButtonActionPerformed(evt);
            }
        });

        createProjectButton.setText("Create Project");
        createProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                createProjectButtonActionPerformed(evt);
            }
        });

        editProjectButton.setText("Update Project");
        editProjectButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editProjectButtonActionPerformed(evt);
            }
        });

        editInfoButton.setText("Edit User Info");
        editInfoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                editInfoButtonActionPerformed(evt);
            }
        });

        addNewUserButton.setText("Add New User");
        addNewUserButton.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                addNewUserButtonMouseClicked(evt);
            }
        });

        communicationButton.setText("Communication");
        communicationButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                communicationButtonActionPerformed(evt);
            }
        });

        lgButton.setText("Logout");
        lgButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lgButtonActionPerformed(evt);
            }
        });

        addMember.setText("Add Member");
        addMember.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addMemberActionPerformed(evt);
            }
        });

        jButton1.setText("Propose Project");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jButton1, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(communicationButton, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                    .addComponent(searchButton, javax.swing.GroupLayout.DEFAULT_SIZE, 142, Short.MAX_VALUE)
                    .addComponent(addNewUserButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editProjectButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(createProjectButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(editInfoButton, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(addMember, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lgButton, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(352, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(createProjectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editInfoButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(editProjectButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(addNewUserButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(searchButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(communicationButton)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(addMember)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lgButton)
                .addContainerGap(179, Short.MAX_VALUE))
        );

        jPanel4.add(jPanel3);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(204, 0, 0), 3));
        jPanel2.setForeground(new java.awt.Color(204, 0, 0));
        jPanel2.setLayout(new java.awt.BorderLayout());
        jPanel4.add(jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, 0)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 1020, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
            .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 471, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void searchButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButtonActionPerformed
        // TODO add your handling code here:
         ma=new MasterPanelFOrProjectPage();
      javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                ma.createAndShowGUI();
            }
        });

    }//GEN-LAST:event_searchButtonActionPerformed

    private void createProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_createProjectButtonActionPerformed
        // TODO add your handling code here:
        cards.setVisible(true);
        CardLayout cl = (CardLayout) (cards.getLayout());
        cl.show(cards, createProject);
    }//GEN-LAST:event_createProjectButtonActionPerformed


    private void editInfoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editInfoButtonActionPerformed
        // TODO add your handling code here:
        cards.setVisible(true);
        CardLayout cl = (CardLayout) (cards.getLayout());
        cl.show(cards, personalInfoPage);
    }//GEN-LAST:event_editInfoButtonActionPerformed

    private void editProjectButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_editProjectButtonActionPerformed
        // TODO add your handling code here:
        
      cards.setVisible(true);
        CardLayout cl = (CardLayout) (cards.getLayout());
        cl.show(cards, editProject);

    }//GEN-LAST:event_editProjectButtonActionPerformed

    private void addMemberActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addMemberActionPerformed
        // TODO add your handling code here:
        cards.setVisible(true);
        CardLayout cl = (CardLayout) (cards.getLayout());
        cl.show(cards, memberPage);
    }//GEN-LAST:event_addMemberActionPerformed

    private void communicationButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_communicationButtonActionPerformed
        // TODO add your handling code here:
            cm=new CommunicationMain();
          
      javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                cm.createAndShowGUI();
            }
        });
        
    }//GEN-LAST:event_communicationButtonActionPerformed

    private void lgButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lgButtonActionPerformed
        // TODO add your handling code here:
        
        LaunchApplication la=new LaunchApplication();
         frame.dispose();
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                la.createAndShowGUI();
            }
        });
        
    }//GEN-LAST:event_lgButtonActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed
 
    private void addNewUserButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addNewUserButtonActionPerformed
        // TODO add your handling code here:
         //add=new AddUserInfoGUIJframe();
        //add.setVisible(true);
       
        
    }//GEN-LAST:event_addNewUserButtonActionPerformed

    private void addNewUserButtonMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_addNewUserButtonMouseClicked
        // TODO add your handling code here:
        add=new AddUserInfoGUIJframe();
        add.setVisible(true);
    }//GEN-LAST:event_addNewUserButtonMouseClicked


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton addMember;
    public javax.swing.JButton addNewUserButton;
    public javax.swing.JButton communicationButton;
    public javax.swing.JButton createProjectButton;
    public javax.swing.JButton editInfoButton;
    public javax.swing.JButton editProjectButton;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    public javax.swing.JLabel jLabel2;
    public javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JButton lgButton;
    public javax.swing.JButton searchButton;
    // End of variables declaration//GEN-END:variables
public static void createAndShowGUI() {
        //Create and set up the window.
        frame = new JFrame("Frugal Lab Application");
        frame.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

        //Create and set up the content pane.
        ProfilePage demo = new ProfilePage();
        demo.addComponentToPane(frame.getContentPane());

        //Display the window.
        frame.pack();
        frame.setSize(1800, 1600);
        frame.setVisible(true);

    }

    public static void main(String[] args) {
        /* Use an appropriate Look and Feel */
        try {
            //UIManager.setLookAndFeel("com.sun.java.swing.plaf.windows.WindowsLookAndFeel");
            UIManager.setLookAndFeel("javax.swing.plaf.metal.MetalLookAndFeel");
        } catch (UnsupportedLookAndFeelException ex) {
            ex.printStackTrace();
        } catch (IllegalAccessException ex) {
            ex.printStackTrace();
        } catch (InstantiationException ex) {
            ex.printStackTrace();
        } catch (ClassNotFoundException ex) {
            ex.printStackTrace();
        }
        /* Turn off metal's use of bold fonts */
        UIManager.put("swing.boldMetal", Boolean.FALSE);

        //Schedule a job for the event dispatch thread:
        //creating and showing this application's GUI.
        javax.swing.SwingUtilities.invokeLater(new Runnable() {
            public void run() {
                createAndShowGUI();
            }
        });
    }
}
